### ISSUE TITLE
Small correction

### ISSUE THREAD

**Issue by superjcvd** [fengalin/raspdac-on-osmc#1]
Hello

First of all thank you for this great work !
I was looking for such project for long time.

I tried to install Kodi + Raspbian on my RaspDAC but I had a lot of issues.
I was never able to make LCD work (after compiling it was crashing the OS)
And for the power button I did something like you did but without the shutdown script
(I was just sending 'sudo halt' command when the button was pressed and I wasn't managing the GPIO04 status)

Anyway I'd like to add a small update to the documentation:

When you do:
`sudo apt-get install gcc python-dev python-pip
sudo pip install rpi.gpio`

You should add:
`sudo apt-get install gcc python-dev python-pip
sudo apt-get install python-setuptools
sudo pip install rpi.gpio`

(pyhton-setuptools is not installed automatically)

regards

**Comment by fengalin** [comment]
Thank you for your feedback @superjcvd!

Do you want to open a PR for this?

**Comment by fengalin** [comment]
Done! Thanks
